<a href="https://colab.research.google.com/github/joaopemenezes/Portfolio-/blob/main/PROJETO_RH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##Tratando Dados
import pandas as pd
import numpy as np
df = pd.read_excel("/content/funcionarios_rh.xlsx")
df.head()
##Informção  sobre a tabela
print(df.info())
## Valores em brancos
contagem = df.isnull().sum()
porcetagem = contagem / len(df)

##Valores duplicados
Duplicados = pd.DataFrame({
    "valores_duplicados": contagem,
    "Porcentagem": porcetagem,
    "Verifição": contagem.apply(lambda x:"Dados sem valores duplicados" if x == 0 else"Dados com valores duplicados")
})
Duplicados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_funcionario       1500 non-null   object
 1   nome                 1500 non-null   object
 2   genero               1500 non-null   object
 3   idade                1500 non-null   int64
 4   departamento         1500 non-null   object
 5   cargo                1500 non-null   object
 6   salario              1500 non-null   float64
 7   tempo_empresa_meses  1500 non-null   int64
 8   satisfacao           1500 non-null   int64
 9   desempenho           1500 non-null   int64
 10  horas_extras         1500 non-null   object
 11  status               1500 non-null   object
 12  motivo_desligamento  400 non-null    object
dtypes: float64(1), int64(4), object(8)
memory usage: 152.5+ KB
None

,valores_duplicados,Porcentagem,Verifição
id_funcionario,0,0.000000,Dados sem valores duplicados
nome,0,0.000000,Dados sem valores duplicados
genero,0,0.000000,Dados sem valores duplicados
idade,0,0.000000,Dados sem valores duplicados
departamento,0,0.000000,Dados sem valores duplicados
cargo,0,0.000000,Dados sem valores duplicados
salario,0,0.000000,Dados sem valores duplicados
tempo_empresa_meses,0,0.000000,Dados sem valores duplicados
satisfacao,0,0.000000,Dados sem valores duplicados
desempenho,0,0.000000,Dados sem valores duplicados
horas_extras,0,0.000000,Dados sem valores duplicados
status,0,0.000000,Dados sem valores duplicados
motivo_desligamento,1100,0.733333,Dados com valores duplicados

In [ ]:
#Quantidade de funcionarios ativos hoje=
df["status"].eq("Ativo").sum()
#Média salarial
df["salario"].mean()

np.float64(6174.513493333332)

In [ ]:
#Quero saber quantos funcionários temos por departamento e por cargo. Faz uma tabela cruzada pra eu ver a distribuição
deo_car = pd.crosstab(df["departamento"], df["cargo"])
deo_car

cargo,Analista Jr,Analista Pleno,Analista Sr,Coordenador,Estagiário,Gerente
departamento,,,,,,
Atendimento,66,63,21,36,11,21
Financeiro,72,62,29,20,18,21
Marketing,56,60,28,24,21,15
Operações,72,69,24,27,19,18
RH,64,65,26,29,15,13
TI,74,43,38,30,13,17
Vendas,57,64,33,17,10,19

In [ ]:
#Preciso da lista dos 15 salários mais altos da empresa, com nome, cargo e departamento, ordenada do maior pro menor
df[["cargo", "departamento","salario"]].sort_values(by ="salario", ascending=False).head(15)

        cargo departamento   salario
732   Gerente  Atendimento  19995.31
527   Gerente           RH  19983.47
266   Gerente       Vendas  19973.09
819   Gerente           RH  19939.87
915   Gerente           TI  19839.76
1143  Gerente    Operações  19772.26
685   Gerente    Operações  19771.16
849   Gerente  Atendimento  19704.92
244   Gerente    Operações  19603.29
67    Gerente    Marketing  19543.28
128   Gerente  Atendimento  19489.24
680   Gerente    Marketing  19298.91
204   Gerente   Financeiro  19243.06
1116  Gerente           TI  19223.16
615   Gerente  Atendimento  19152.79

In [ ]:
#As pessoas estão me falando que o pessoal de Vendas está pedindo demissão. Você consegue confirmar isso com dados? Quero saber qual departamento tem a MAIOR proporção (%) de desligados em relação ao total de funcionários daquele departamento — não em número absoluto, em percentual. E me diz também qual é o principal motivo de desligamento em Vendas

df.groupby()

In [ ]:
df.head()

,id_funcionario,nome,genero,idade,departamento,cargo,salario,tempo_empresa_meses,satisfacao,desempenho,horas_extras,status,motivo_desligamento
0,1,Bruna Aparecida,Masculino,39,Vendas,Analista Sr,7623.62,91,3,2,Sim,Ativo,NaN
1,2,Matheus Guerra,Masculino,51,Vendas,Gerente,17855.95,28,4,1,Sim,Ativo,NaN
2,3,Matteo das Neves,Feminino,27,TI,Analista Jr,2734.03,6,2,4,Não,Ativo,NaN
3,4,Dante Freitas,Feminino,43,Operações,Coordenador,8232.33,61,3,3,Sim,Ativo,NaN
4,5,Rebeca Souza,Feminino,26,Vendas,Analista Jr,3401.67,37,3,5,Sim,Desligado,Insatisfação com liderança

In [ ]:
#As pessoas estão me falando que o pessoal de Vendas está pedindo demissão. Você consegue confirmar isso com dados? Quero saber qual departamento tem a MAIOR proporção (%) de desligados em relação ao total de funcionários daquele departamento — não em número absoluto, em percentual. E me diz também qual é o principal motivo de desligamento em Vendas
resultado = df.groupby("departamento").agg(
    demissao = ("status", lambda x: (x=="Desligado").sum()),
    total = ("status", "size")
)
resultado["porcertagem"] = resultado["demissao"] / resultado["total"]
resultado["porcertagem"]

departamento
Atendimento    0.316514
Financeiro     0.211712
Marketing      0.279412
Operações      0.235808
RH             0.202830
TI             0.246512
Vendas         0.385000
Name: porcertagem, dtype: float64

In [ ]:
#Queria comparar a satisfação média de quem faz hora extra com a de quem não faz. Se possível, quebra isso por departamento também, porque acho que no meu setor é diferente do resto
satisfação_dep = df.groupby(["horas_extras","departamento"])["satisfacao"].mean().unstack()

In [ ]:
df.groupby("cargo")["desempenho"].agg(
    ["mean", "std"]
)

                    mean       std
cargo
Analista Jr     3.058568  1.413767
Analista Pleno  2.974178  1.399761
Analista Sr     2.989950  1.396207
Coordenador     3.098361  1.395104
Estagiário      2.803738  1.450044
Gerente         3.185484  1.455949

In [ ]:
#Separa os funcionários ativos do meu departamento em faixas: até 1 ano de casa, de 1 a 3 anos, e mais de 3 anos. Quero saber quantos tem em cada faixa
operacao_ativos  = df.loc[(df["departamento"] == "Operações") & (df["status"] == "Ativo")].copy()
operacao_ativos["tempo_empresa"] = pd.cut(operacao_ativos["tempo_empresa_meses"], bins= [- np.inf,12,36,df['tempo_empresa_meses'].max()], labels=["Até 1 ano",
        "De 1 a 3 anos",
        "Mais de 3 anos"])
operacao_ativos["tempo_empresa"]

3       Mais de 3 anos
6            Até 1 ano
14           Até 1 ano
22       De 1 a 3 anos
23       De 1 a 3 anos
             ...
1463    Mais de 3 anos
1464     De 1 a 3 anos
1471    Mais de 3 anos
1493     De 1 a 3 anos
1499    Mais de 3 anos
Name: tempo_empresa, Length: 175, dtype: category
Categories (3, object): ['Até 1 ano' < 'De 1 a 3 anos' < 'Mais de 3 anos']

In [ ]:
# infromação sobre determinada
df.iloc[1498]

id_funcionario                  1499
nome                   Milena da Luz
genero                      Feminino
idade                             44
departamento               Marketing
cargo                    Coordenador
salario                      8629.09
tempo_empresa_meses               12
satisfacao                         2
desempenho                         1
horas_extras                     Não
status                         Ativo
motivo_desligamento              NaN
Name: 1498, dtype: object

In [ ]:
bins = [-np.inf, 12, 36, np.inf]
labels = ["Ate 1 ano", "Até 3 anos", "Maiores 3 anos"]
operacoes_ativos = df["Quantidade tempo"] = pd.cut(df["tempo_empresa_meses"], bins = bins, labels= labels)

,id_funcionario,nome,genero,idade,departamento,cargo,salario,tempo_empresa_meses,satisfacao,desempenho,horas_extras,status,motivo_desligamento,Quantidade tempo
0,1,Bruna Aparecida,Masculino,39,Vendas,Analista Sr,7623.62,91,3,2,Sim,Ativo,NaN,Maiores 3 anos
1,2,Matheus Guerra,Masculino,51,Vendas,Gerente,17855.95,28,4,1,Sim,Ativo,NaN,Até 3 anos
2,3,Matteo das Neves,Feminino,27,TI,Analista Jr,2734.03,6,2,4,Não,Ativo,NaN,Ate 1 ano
3,4,Dante Freitas,Feminino,43,Operações,Coordenador,8232.33,61,3,3,Sim,Ativo,NaN,Maiores 3 anos
4,5,Rebeca Souza,Feminino,26,Vendas,Analista Jr,3401.67,37,3,5,Sim,Desligado,Insatisfação com liderança,Maiores 3 anos
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1496,Gael Henrique da Conceição,Feminino,32,TI,Analista Sr,7037.77,49,2,2,Sim,Ativo,NaN,Maiores 3 anos
1496,1497,Ayla Nogueira,Feminino,26,Marketing,Analista Jr,3329.06,16,4,2,Não,Ativo,NaN,Até 3 anos
1497,1498,Ravi Rodrigues,Feminino,23,RH,Estagiário,1305.37,61,4,3,Sim,Ativo,NaN,Maiores 3 anos
1498,1499,Milena da Luz,Feminino,44,Marketing,Coordenador,8629.09,12,2,1,Não,Ativo,NaN,Ate 1 ano
1499,17:34:00,Maria Luísa Dias,Masculino,31,Operações,Analista Pleno,4725.11,62,3,3,Sim,Ativo,NaN,Maiores 3 anos